// Code generated by github.com/arsmn/fastgql, DO NOT EDIT.

package model

import (
	"fio_service/structs"
)

type NewFio struct {
	Name       string  `json:"name"`
	Surname    string  `json:"surname"`
	Patronymic *string `json:"patronymic"`
}

type SearchData struct {
	Name        *string `json:"name"`
	Surname     *string `json:"surname"`
	Patronymic  *string `json:"patronymic"`
	AgeDown     *int    `json:"age_down"`
	AgeUp       *int    `json:"age_up"`
	Gender      *string `json:"gender"`
	Nationality *string `json:"nationality"`
}

type Status struct {
	Error bool    `json:"error"`
	Msg   *string `json:"msg"`
}

type UpdateFio struct {
	ID          int     `json:"id"`
	Name        *string `json:"name"`
	Surname     *string `json:"surname"`
	Patronymic  *string `json:"patronymic"`
	Age         *int    `json:"age"`
	Gender      *string `json:"gender"`
	Nationality *string `json:"nationality"`
}

type UsersResponse struct {
	Error    bool           `json:"error"`
	Msg      *string        `json:"msg"`
	UserList []*structs.FIO `json:"user_list"`
}
